server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /springboot-template-ms
spring:
  main:
    banner-mode: off
  application:
    name: springboot-template-ms
  cloud:
    kubernetes:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0
    log:
      slf4j:
        whitelisted-mdc-keys: principal
        enabled: true
    baggage-keys: principal
  profiles:
    include: actuator